name: Deploy Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
  issues:
    types: [opened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" | base64 --decode > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Pull Deploy Hub
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'

          cd /home/ubuntu/deploy_hub && git pull origin master --no-rebase

          echo "Pulled Deploy Hub repository."

          EOF

      - name: Pull Forest Portfolio Docker Image
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'

          echo "Pulling Forest Portfolio Docker image."

          docker login

          docker pull sahanlahiru/sahan:forest

          EOF

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'

          cd /home/ubuntu/deploy_hub && docker-compose down

          cd /home/ubuntu/deploy_hub && docker-compose up -d --build

          echo "Deployed application with Docker Compose."

          EOF

      - name: Cleanup SSH Key
        if: always()
        run: rm -f ~/.ssh/deploy_key
